definitions:
  dto.NetworkInterface:
    properties:
      address:
        type: string
      default_gateway:
        type: boolean
      desc:
        type: string
    type: object
  resp.DataResp:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact:
    email: cloverzrg@gmail.com
    name: API Support
    url: https://github.com/cloverzrg/go-portforward
  license:
    name: go-portforward
  title: go-portforward
  version: "1.0"
paths:
  /v1/network/interfaces:
    get:
      description: '""'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/resp.DataResp'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.NetworkInterface'
                  type: array
              type: object
      summary: get network interface list
      tags:
      - network
swagger: "2.0"
